### ISSUE TITLE
to-do.live.com not working anymore

### ISSUE THREAD

**Issue by TheManohar** [jiahaog/nativefier#1032]
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [X] I searched existing issues, open & closed. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

logging in and having a working app on to-do.live.com is not working anymore.
It was working with an older version of nativefier, but since the last 2 updates new nativefier apps made on to-do.live.com are not working anymore.

**Steps to reproduce**
just run: nativefier --name "To Do" "https://todo.microsoft.com"
and try to login with your account

**Expected behavior**

Login on external browser, then get login on nativefier app

**Actual behavior**

Login only happens on external browser, but nativefier is stuck loading forever

**Debug info**

none

**Context**

 - Nativefier: 9.2.0

**Comment by TheManohar** [comment]
solved the issue with re-making the nativefier app with --block-external-urls

**Comment by ronjouch** [comment]
> solved the issue with re-making the nativefier app with --block-external-urls

👍, I was about to suggest https://github.com/jiahaog/nativefier/blob/master/docs/api.md#internal-urls . `--block-external-urls` is a bit more heavy-handed.
